### ISSUE TITLE
Empty sets should be allowed as input

### ISSUE THREAD

**Issue by alecjacobson** [iheartla/iheartla#46]
Currently the codegen adds an assertion (e.g., for python)

    assert isinstance(E, list) and len(E) > 0  

Shouldn't this be 

    assert isinstance(E, list) and len(E) >= 0  
?

For example, it is perfectly valid to build the (all-zero) adjacency matrix of an empty set of edges.

**Comment by yig** [comment]
Asserting that it is an instance of a list is too strict a check for Python. I would simply write `E = list(E)` if you want to use `E` as a list, or just let it be without the assert statement so long as the type of `E` supports whatever we call on it (`len()` and iteration or indexing). This essentially lets E be a templated type.

A different question is whether we want sets to be true sets (unique elements only) or to allow duplicate elements (more like sequences).

**Comment by yig** [comment]
If we want a true set, in Python we can do `E = set(E)` (or `E = frozenset(E)` for an immutable set type). If we want to keep the input generic ("templated"), we can just check that the size is right with `assert len(E) == len(frozenset(E))`.

**Comment by pressureless** [comment]
We used `set` in C++, so maybe `E = frozenset(E)` is a better choice.
Do we need to check the size of each element in a `set` for Python? 
In C++, the type definition ensures this.
`std::set<std::tuple< int, int > >` or `std::set<std::tuple< int, int, int > >`

**Comment by yig** [comment]
We could check the size in Python with `assert all( len(el) == n for el in E )`

**Comment by pressureless** [comment]
Fixed
