### ISSUE TITLE
Use ² to square norm

### ISSUE THREAD

**Issue by alecjacobson** [iheartla/iheartla#72]
```
‖ [1 1] ‖_F²
```
should parse the same as
```
‖ [1 1] ‖_F^2
```

I'd even say these `_F` and `^2`/`²`should be exchangeable for norms:
```
‖ [1 1] ‖^2_F
```
and
```
‖ [1 1] ‖²_F
```

Currently, I❤️LA seems confused trying to parse `F²` as a type of norm."
```
Error on line 1 at column 11. Norm error. Invalid norm for Matrix.
‖ [1 1] ‖_F²
          ^
```

**Comment by pressureless** [comment]
Fixed
