### ISSUE TITLE
[feature request] Support both sets unicode symbols for inequalities

### ISSUE THREAD

**Issue by alecjacobson** [iheartla/iheartla#73]
Currently we support `≤` and `≥` for less than or equals to and greater than or equals to.

Apparently there are also `⩽` and `⩾`. In unicode, these are called [Greater-Than or Slanted Equal To](https://www.compart.com/en/unicode/U+2A7E). Not sure if in conventionally written math these would mean something different. If not, we should simply treat them as the usual ones.

Currently we throw a parse error message, e.g.,

```
Error on line 1 at column 30. Failed to parse solver: no available options
∑_i α_i + 1/M ∑_i ∑_(j for j ⩽ n_i) (f(X_i,j)/`p_c`(X_i,j) - (∑_k α_k p_k(X_i,j))/`p_c`(X_i,j))
                             ^
```

**Comment by pressureless** [comment]
I used `⩽` previously, the symbol can't show up on Overleaf so I changed to `≤`, I'll support both.
