### ISSUE TITLE
Shadowing `I` not working

### ISSUE THREAD

**Issue by alecjacobson** [iheartla/iheartla#89]
By default `I` means the identity matrix, but we should be able to shadow/obscure it with a parameter. That is,

```
given
I ∈ ℝ²

I_1+I_2
```
should compile the same as
```
given
X ∈ ℝ²

X_1+X_2
```
instead the former gives the error:
```
Error on line 4 at column 1. You can't use 'I' with subscript since it has been defined before.
I_1+I_2
^
```

**Comment by pressureless** [comment]
I believe we haven't got to the indexing rule when implementing this.
The simple case will work.
```
given
I ∈ ℝ

I + I
```
I'll fix later

**Comment by pressureless** [comment]
Fixed
